Repository ovh-ux/ovh-module-sharepoint, pull requests merged in 2018-11, with the labels that each got.

#69 Update readme
  README.md
Labels: enhancement

#71 fix(products): remove use of Products service
  package.json
  src/sharepoint/account/password/update/sharepoint-account-password-update.controller.js
  src/sharepoint/account/sharepoint-account.controller.js
  src/sharepoint/domain/add/sharepoint-domain-add.controller.js
  src/sharepoint/information/INFORMATION.html
  src/sharepoint/information/sharepoint-information.controller.js
  src/sharepoint/order/sharepoint-order.controller.js
  src/sharepoint/sharepoint-tabs.controller.js
  src/sharepoint/sharepoint.app.js
  src/sharepoint/sharepoint.controller.js
  src/sharepoint/sharepoint.service.js
  yarn.lock
Labels: :santa: one-manager, quality check ok

#65 refactor(components.incrementnumber): move to webUniverseComponents
  src/sharepoint/account/add/sharepoint-account-add.html
Labels: :santa: one-manager, quality check ok

#68 refactor(components.validator): move to webUniverseComponents
  src/sharepoint/domain/add/sharepoint-domain-add.controller.js
Labels: :santa: one-manager, quality check ok

#66 refactor(components.loader): replace loader by oui-spinner
  src/sharepoint/order/sharepoint-order.html
  src/sharepoint/renew/update/sharepoint-renew-update.html
Labels: :santa: one-manager, quality check ok

#81 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug

#57 refactor(sharepoint.information): use oui-tile oui-progress
  src/sharepoint/information/INFORMATION.html
  src/sharepoint/information/sharepoint-information.controller.js
  src/sharepoint/translations/Messages_fr_FR.xml
Labels: enhancement

#83 Submit and retrieve translations
  src/sharepoint/translations/Messages_cs_CZ.xml
  src/sharepoint/translations/Messages_de_DE.xml
  src/sharepoint/translations/Messages_en_ASIA.xml
  src/sharepoint/translations/Messages_en_AU.xml
  src/sharepoint/translations/Messages_en_CA.xml
  src/sharepoint/translations/Messages_en_GB.xml
  src/sharepoint/translations/Messages_en_SG.xml
  src/sharepoint/translations/Messages_en_US.xml
  src/sharepoint/translations/Messages_es_ES.xml
  src/sharepoint/translations/Messages_es_US.xml
  src/sharepoint/translations/Messages_fi_FI.xml
  src/sharepoint/translations/Messages_fr_CA.xml
  src/sharepoint/translations/Messages_fr_FR.xml
  src/sharepoint/translations/Messages_it_IT.xml
  src/sharepoint/translations/Messages_lt_LT.xml
  src/sharepoint/translations/Messages_nl_NL.xml
  src/sharepoint/translations/Messages_pl_PL.xml
  src/sharepoint/translations/Messages_pt_PT.xml
Labels: bug
