Repository ovh-ux/ovh-module-sharepoint, pull requests merged in 2019-01, with the labels that each got.

#95 build(eslint): use eslint-formatter-pretty
  package.json
  yarn.lock
Labels: enhancement

#101 fix(users-order): fix for translation of label
  src/sharepoint/account/add/sharepoint-account-add.html
  src/sharepoint/translations/Messages_fr_FR.xml
Labels: bug, quality check ok, translation-required

#91 Feat/sharepoint provider
  package.json
  src/sharepoint/account/ACCOUNT.html
  src/sharepoint/account/add-legacy/sharepoint-account-add-legacy.controller.js
  src/sharepoint/account/add-legacy/sharepoint-account-add-legacy.html
  src/sharepoint/account/add/sharepoint-account-add.controller.js
  src/sharepoint/account/add/sharepoint-account-add.html
  src/sharepoint/account/sharepoint-account.controller.js
  src/sharepoint/order/sharepoint-order.controller.js
  src/sharepoint/order/sharepoint-order.html
  src/sharepoint/sharepoint-order.service.js
  src/sharepoint/sharepoint.app.js
  src/sharepoint/sharepoint.service.js
  src/sharepoint/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok
